
name: deploy to AWS lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm run build --if-present
        env:
          CI: true
#   sonarCloudTrigger:
#     name: SonarCloud Trigger
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKENS }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
