on: push
name: Main Workflow
jobs:
  artifactoryUpload:
    name: Upload Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      run: ./buildmyartifact.sh
    - name: publish to artifactory
      uses: advancedcsg-open/action-jfrog-cli@master
      with:
        url: 'http://54.194.230.60:8081/'
        credentials type: 'user'
        username: ${{ secrets.RT_USER }}
        password: ${{ secrets.RT_PASSWORD }}
        args: u "dist/*" "/mu/repo/path/" --recursive=true --build-name=myawesomeapp
