 
name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        env:
          url: 'http://54.194.230.60:8081/'
          credentials type: 'user'
          username: ${{ secrets.RT_USER }}
          password: ${{ secrets.RT_PASSWORD }}
          
      - name: Run JFrog CLI
        run: |
          # Collect environment variables for the build
          jfrog rt bce
          # Collect VCS details from git and add them to the build
          jfrog rt bag
          # Publish build info
          jfrog rt bp
