name: Build and Publish and Scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  ART_URL: http://54.194.230.60:8081/artifactory/
  ART_USER: admin
  SERVER_ID: ahmad
  CI: true

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: "jfrog install, configure cli"
      run: |
        # Get Jfrog CLI
            echo "Jfrog binary does not exist. Downloading now...."
            curl -fL https://getcli.jfrog.io | sh -s 1.32.4
            sudo mv jfrog /usr/local/bin
        # Configure Jfrog CLI
    - name: "Configure Jfrog"
      run: jfrog rt config $SERVER_ID --url=$ART_URL --user=$ART_USER --password=${{ secrets.RT_PASSWORD }} --interactive=false
