name: deploy to AWS lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@develop
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@develop
        with:
           projectBaseDir: my-function
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm run build --if-present
        env:
          CI: true
#       - name: zip
#         uses: montudor/action-zip@v0.1.0
#         with:
#           args: zip -qq -r ./bundle.zip ./
#       - name: default deploy
#         uses: appleboy/lambda-action@master
#         with:
#           aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws_region: ap-southeast-1
#           function_name: my-function
#           zip_file: bundle.zip
